normal:
  DEBUG: false
  SHOW_TEST_BANNER: false
  EMAIL_HOST_USER : "rocketboyking@gmail.com"
  EMAIL_HOST_PASSWORD : "zwcs smbu iuof jfng"

testing:
  DEBUG: true
  SHOW_TEST_BANNER: true
  EMAIL_HOST_USER : "rocketboyking@gmail.com"
  EMAIL_HOST_PASSWORD : "zwcs smbu iuof jfng"

local:
  DEBUG: true
  SHOW_TEST_BANNER: true
  EMAIL_HOST_USER : "rocketboyking@gmail.com"
  EMAIL_HOST_PASSWORD : "zwcs smbu iuof jfng"